# Generated by Django 4.2.4 on 2023-08-23 13:14

from django.db import migrations, models
import django.db.models.deletion
import ool


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queuing', 'queuing'), ('done', 'done'), ('processing', 'processing'), ('no_handler', 'no_handler'), ('exception', 'exception'), ('cancel', 'cancel')], default='queuing', max_length=20)),
                ('schedule_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', ool.VersionField(default=0)),
            ],
            bases=(ool.VersionedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TimerSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='ytimer.timer')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TimerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ytimer.timer')),
            ],
        ),
    ]
