# Generated by Django 4.2.4 on 2023-08-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('timeout_timer_id', models.UUIDField(blank=True, null=True)),
                ('timeout_in_seconds', models.IntegerField(blank=True, null=True)),
                ('poll_status_timer_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
