# Generated by Django 4.2.4 on 2023-08-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytimer_example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('running', 'running'), ('success', 'success'), ('fail', 'fail'), ('timerout', 'timerout')], default='created', max_length=20),
        ),
    ]
